on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce PR naming convention
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '(fix|feat):\s\[\w{1,8}-\d{1,8}\].*' # (fix: [OR-123] some title of the PR, feat: [OR-1234] some title of the PR)
