name: Preview

env:
  NODE_VERSION: 16
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    environment:
      name: Preview
      url: https://${{ steps.setup.outputs.branch }}.test-docs-cfp.pages.dev

    steps:
      - id: setup
        name: Setup Branch
        uses: actions/github-script@v6
        with:
          script: |
            const cleanBranch = context.ref
              .replace('refs/heads/', '')
              .replace(/[^a-z0-9\-]+/i, '-')
              .replace(/-{2,}/, '-')
              .toLowerCase()
            if (cleanBranch === "") {
              core.setFailed('Unable to determine clean branch name. Blocking to avoid production deploy.')
            } else {
              core.info(`Clean branch is set to ${cleanBranch}`)
            }
            core.setOutput('branch', cleanBranch)

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 16.13.2

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install --frozen-lockfile --non-interactive

      - name: Build
        run: npx turbo run build --api="https://turbocache.msutkowski.com" --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/docs/dist --project-name=test-docs --branch="${{ steps.setup.outputs.branch }}"
  web:
    runs-on: ubuntu-latest

    environment:
      name: Preview
      url: https://${{ steps.setup.outputs.branch }}.test-web-aa8.pages.dev

    steps:
      - id: setup
        name: Setup Branch
        uses: actions/github-script@v6
        with:
          script: |
            const cleanBranch = context.ref
              .replace('refs/heads/', '')
              .replace(/[^a-z0-9\-]+/i, '-')
              .replace(/-{2,}/, '-')
              .toLowerCase()
            if (cleanBranch === "") {
              core.setFailed('Unable to determine clean branch name. Blocking to avoid production deploy.')
            } else {
              core.info(`Clean branch is set to ${cleanBranch}`)
            }
            core.setOutput('branch', cleanBranch)

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 16.13.2

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install --frozen-lockfile --non-interactive

      - name: Build
        run: npx turbo run build --api="https://turbocache.msutkowski.com" --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/web/dist --project-name=test-web --branch="${{ steps.setup.outputs.branch }}"
