name: Production

env:
  NODE_VERSION: 16
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:
    inputs:
      app:
        description: "The app to manually deploy"
        required: true
        type: choice
        options:
          - docs
          - web

jobs:
  web:
    if: ${{ startsWith(github.event.release.tag_name, 'web-') || github.event.inputs.app == 'web' }}
    environment:
      name: Web Production
      url: https://web.msutkowski.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   id: cache-nodemodules
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --filter=web --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/web/dist --project-name=test-web --commit-hash=${{github.sha}} --commit-dirty=true
  docs:
    if: ${{ startsWith(github.event.release.tag_name, 'docs-') || github.event.inputs.app == 'docs' }}
    environment:
      name: Docs Production
      url: https://docs.web.msutkowski.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   id: cache-nodemodules
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --filter=docs --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/docs/dist --project-name=test-docs --branch="main" --commit-hash=${{github.sha}} --commit-dirty=true
