name: Production

env:
  NODE_VERSION: 16
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:
    inputs:
      apps:
        description: "The app to manually deploy"
        required: true
        type: choice
        options:
          - docs
          - web

jobs:
  logger:
    runs-on: ubuntu-latest

    steps:
      - name: basic print logging
        run: |
          echo "selected app - ${{ github.event.inputs.app }}"
          echo "tag_name - ${{ github.event.tag_name }}"

  web:
    if: ${{ startsWith(github.event.tag_name, 'web-') || github.event.inputs.app == 'web' }}
    environment:
      name: Web Production
      url: https://web.msutkowski.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npx turbo run build --filter=web --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/web/dist --project-name=test-web
  docs:
    if: ${{ startsWith(github.event.tag_name, 'docs-') || github.event.inputs.app == 'docs' }}
    environment:
      name: Docs Production
      url: https://docs.web.msutkowski.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-nodemodules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npx turbo run build --filter=docs --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/docs/dist --project-name=test-docs
