on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v3
        with:
          release-type: node
          monorepo-tags: true
          command: manifest
          token: ${{ secrets.GH_PAT }}
