on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-apis/release-please-action@v4
        with:
          release-type: node
          include-component-in-tag: true
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GH_PAT }}
