name: Staging

env:
  NODE_VERSION: 16
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      web: ${{ steps.filter.outputs.web }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v2
        with:
          # We're trying to replicate Vercel's Ignore Build feature here and they do a depth of 10.
          fetch-depth: 10
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
            docs:
              - 'apps/docs/**'
            ui:
              - 'packages/ui/**'

  web:
    environment:
      name: Web Staging
      url: https://staging.web.msutkowski.com
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' || needs.changes.outputs.ui == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --filter=web --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/web/dist --project-name=test-web --branch="staging"  --commit-hash="${{github.sha}}"
  docs:
    environment:
      name: Docs Staging
      url: https://docs.web.msutkowski.com
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' || needs.changes.outputs.ui == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --filter=docs --token="${{ env.TURBO_TOKEN }}"

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish ./apps/docs/dist --project-name=test-docs --branch="staging" --commit-hash="${{github.sha}}"
